version: '3.8'

services:
  container_name: user-service-db
      image: postgres
      ports:
        - '5432:5432'
      restart: unless-stopped
      env_file:
        - user-service/user-service-db-credentials.env