version: '3.8'

services:
  user-service-db:
    container_name: user_service_db
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - user-service/user-service-db-credentials.env
