version: '3.8'

services:
  user-service:
    container_name: user-service
    build:
      context: ../
      dockerfile: docker/user-service/Dockerfile
    ports:
      - '8000:8000'

  user-service-db:
    container_name: user-service-db
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    env_file:
      - user-service/user-service-db-credentials.env
