version: '3.8'

services:
  user-service:
    container_name: user_service
    build:
      context: ../
      dockerfile: docker/user-service/Dockerfile
    ports:
      - '8000:8000'

  alethia-service:
    container_name: alethia_service
    build:
      context: ../
      dockerfile: docker/alethia-service/Dockerfile
    ports:
      - '8001:8001'

  # The purpose of this container is to open up alethia-service to the internet. This will allow me to test webhooks
  ngrok-test-webhooks:
    container_name: ngrok_test_webhooks
    image: shkoliar/ngrok:latest
    ports:
      - '4551:4551'
    links:
      - alethia-service
    environment:
      - REGION=eu
      - DEBUG=true
      - DOMAIN=alethia_service
      - PORT=8001
    depends_on:
      -   alethia-service
